language: python

matrix:
  exclude:
  - python: 3.2
    env: LMDB_FORCE_CPYTHON=1
  - python: pypy
    env: LMDB_FORCE_CPYTHON=1

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly
  - pypy

env:
  - LMDB_FORCE_CFFI=1
  - LMDB_FORCE_CPYTHON=1
install:
  - sudo apt-get install gdb
  - pip install cffi

  - python setup.py develop
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install -I py==1.4.20 pytest==2.5.2; fi
before_script:
  - source misc/helpers.sh

script:
  - >
    if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]];
      then
        sudo ./misc/runtests-travisci.sh
      else
        with_gdb python -m pytest tests;
    fi

notifications:
  email: false
